### ISSUE TITLE
does not sync at all

### ISSUE THREAD

**Issue by reyestrada** [memen45/SubMusic#23]
When I try sync, it always got stuck at "Syncing SubMusic 0% Complete"

Environment:
Garmin 645 Music v7.00 (e036468)
Nextcloud 21.0.0 (Jail in TrueNAS-12.0-U2.1)
subsonic http://<URL>:<PORT>/apps/music/subsonic (I'm not using https, can that cause the issue??)

![Screenshot from 2021-04-09 23-18-24](https://user-images.githubusercontent.com/8662942/114260532-4fe6e280-998a-11eb-82b8-3f6812cde9dc.png)

Also, it seems it leaves the WiFi connection hanging around because the device battery drain really fast after I try to sync

Another consideration, is that initially, the sync attempt fail (-300 "NETWORK_REQUEST_TIMED_OUT"), to get around that, I need to open the device options settings -> music -> Music Providers -> SubMusic -> Settings (yes, again) -> Music -> Music Providers -> SubMusic -> Manage -> Music Providers -> SubMusic; seems like if I do it this way, is able to start wifi connection, at this point, I can test the server connection and it's fine, but sync does not seems to work at all.

**Comment by memen45** [comment]
See #22, probably your device is requiring https connection. It is interesting though that one of the two sync possibilities does not show errors correctly and hangs at 0%. I think both should interrupt and show the error -300.

Let me know if switching to https solves your problem (certbot with letsencrypt makes it very easy to enable https on your site). Since you are using Nextcloud, I would recommend using the Ampache backend, as it allows larger playlist to synchronize at once.

From #22:

A similar [report](https://forums.garmin.com/developer/connect-iq/f/discussion/166139/error--300) on the Garmin developer forum. It seems like some devices are requiring https connection. This could be due to the Garmin Connect Mobile version and operating system (iOS is more strict than Android).

The documentation states a -1001 error indicates https requirements, but as the report states, in practice it results in a -300 network timeout.

Unfortunately, as a developer I cannot circumvent these limitations. I would recommend using https on your site if possible. I should note that self-signed certificates are also not supported on Garmin watches. 

_Originally posted by @memen45 in https://github.com/memen45/SubMusic/issues/22#issuecomment-809971062_

**Comment by reyestrada** [comment]
Wow! what a fast and detailed reply. I will try to setup my nextcloud with https and I will let you know the result.
Regards

**Comment by cristianpb** [comment]
An update about #22 
I added https using self signed certificates but I still obtain the same error 300 network timeout. I think garmin doesn't like self signed certificates.

However, when using ngrok to obtain a https connection, I'm able to get the server name without the 300 error and read the playlists in my airsonic server. But when I try to sync a playlist I'm stuck at 0% and also when I try to do the server test I obtain the following messages:

* inlog OK
* 402 network response too_large

**Comment by memen45** [comment]
Please comment in the corresponding issue thread to keep conversations separated. Your network response too large error can be solved by reducing the number of songs on the playlist. Typically the limit is around 25 songs, but it depends on the amount of metadata stored for each of the songs. You can still sync all the songs by splitting them up in multiple playlists of ~25 songs. If you are not tied to Airsonic, you might want to consider [Ampache](https://github.com/ampache/ampache) as your server backend. The Ampache API is much better and allows for 'unlimited' playlist size (limited by watch storage of course).

> Another consideration, is that initially, the sync attempt fail (-300 "NETWORK_REQUEST_TIMED_OUT"), to get around that, I need to open the device options settings -> music -> Music Providers -> SubMusic -> Settings (yes, again) -> Music -> Music Providers -> SubMusic -> Manage -> Music Providers -> SubMusic; seems like if I do it this way, is able to start wifi connection, at this point, I can test the server connection and it's fine, but sync does not seems to work at all.

Are you able to access the Playback Menu? It should be easier to access and from there you can choose "More" and then "Sync".

**Comment by cristianpb** [comment]
I deployed Ampache to replace airsonic, then used the same technique of @reyestrada :

>Another consideration, is that initially, the sync attempt fail (-300 "NETWORK_REQUEST_TIMED_OUT"), to get around that, I need to open the device options settings -> music -> Music Providers -> SubMusic -> Settings (yes, again) -> Music -> Music Providers -> SubMusic -> Manage -> Music Providers -> SubMusic; seems like if I do it this way, is able to start wifi connection, at this point, I can test the server connection and it's fine, but sync does not seems to work at all.

This actually allows me to past the server test using http connection. But then I got the same problem of this issue, sync stays at 0%. Even for playlist of 2 songs. 

![sync](https://user-images.githubusercontent.com/18708179/114278030-68d7ae00-99f3-11eb-9dd8-c20176012b62.jpg)

**Comment by reyestrada** [comment]
I enabled https but I'm still unable to make that work, not sure if the implementation I did is not correct, but the errors I'm getting now are (note that I'm using https with an internal IP, but I created the cert with certbot with a valid dns name and I made it public for validation but after that I just use that with internal IP):

- Test failed: 0 "UNKNOWN_ERROR"
- 0 "UNKNOWN_ERROR"

The way I implemented https was:
- Created a new VM with ubuntu 20.04
- Install haproxy and certbot
- Created a new cert for 1 subdomain I use
- Configured ha proxy to redirect requests to the actual nextcloud endpoint
- In nextcloud, I added the subdomain I configured and the IP of the HA proxy VM to /usr/local/www/nextcloud/config/config.php (restart nginx)

![IMG_20210411_010845](https://user-images.githubusercontent.com/8662942/114314671-73a44880-9ab0-11eb-9541-b1c6431b295d.jpg)

![IMG_20210411_010917](https://user-images.githubusercontent.com/8662942/114314681-799a2980-9ab0-11eb-900e-b447ae4e66f9.jpg)

If I have time, I'll do more tests, but I feel stuck at the moment. If someone has an idea of what to test, please let me know.

Regards

**Comment by memen45** [comment]
SSL certificates are tied to the address you requested them for. You cannot install certificates for domain.com and then access the server by its ip address, the certificates will be incorrect (you access e.g. 192.168.102.23 and the server replies 'yes I am domain.com'... that does not make you trust the server). A typical browser will show you warnings as well, so the watch will not accept it.

So, if you have https on example.domain.com, you need to enter e.g. `https://example.domain.com/apps/music/ampache` for the url in the connect iq settings. Let me know if that works for you! You can check if your certificate was installed correctly by using your browser again.

**Comment by reyestrada** [comment]
Right. I did configure the address to the watch using the dns name, intially I deployed a small dns internally (pihole with local dns entry), but since I'm using noip, I also did set the domain with the local IP address of HA Proxy in another of my tests. The issue shown above is with this setup.

**Comment by memen45** [comment]
Can you test your watch against the Ampache demo server? Just to see if it is your server setup or the watch settings.

**Comment by reyestrada** [comment]
I used nextcloud, it gives me 2 endpoints, 1 for subsonic and another for ampache. Ampache did not even went this far. If you give me another server setup, I will set that up and test in my free time and I can post the results. At this point I'm starting to think it's the nextcloud/endpoints issue. 

I really appreciate your support!! Thank you very much

**Comment by memen45** [comment]
Check https://ampache.org/demo.html

**Comment by reyestrada** [comment]
I tested the demo instance from ampache and it still not working.

![image](https://user-images.githubusercontent.com/8662942/114685697-f4d52880-9cc6-11eb-8f33-8b3331d34dd3.png)


I also noticed I had to do the same I posted before

> Another consideration, is that initially, the sync attempt fail (-300 "NETWORK_REQUEST_TIMED_OUT"), to get around that, I need to open the device options settings -> music -> Music Providers -> SubMusic -> Settings (yes, again) -> Music -> Music Providers -> SubMusic -> Manage -> Music Providers -> SubMusic; seems like if I do it this way, is able to start wifi connection, at this point, I can test the server connection and it's fine, but sync does not seems to work at all.

but this time I found a quicker way for that:
Music button (hold down button) -> Settings (hold up) -> Music Providers -> Subsonic -> Manage -> Music Providers -> SubMusic

Test is ok
![image](https://user-images.githubusercontent.com/8662942/114685575-db33e100-9cc6-11eb-9b54-621525c7046f.png)

![image](https://user-images.githubusercontent.com/8662942/114685623-e5ee7600-9cc6-11eb-901e-cd069912888d.png)

I can even see and select playlists to sync
![image](https://user-images.githubusercontent.com/8662942/114685819-0cacac80-9cc7-11eb-9a25-2b5c133515f0.png)

But if I try to sync, it stays in "Searching for Wi-Fi network." forever
![image](https://user-images.githubusercontent.com/8662942/114685931-2a7a1180-9cc7-11eb-8071-18cb9ef34d21.png)

Something I noticed, is that my watch kind of miss-behave after I try to sync, battery die way too fast, and if I shut it down, sometimes it stays in like shutting down forever, and I need to shutdown pressing the light button for more than 15 seconds

I think something on the software on the watch isn't working with the current version of Subsonic.

This is my update. I hope this helps to track down the issue.
Thanks for all your support on this!

Regards

**Comment by memen45** [comment]
Thanks a lot for your feedback. The sync seems to require active wifi connection. Do you have a wifi network setup on your watch?

Also, due to some issues with the Auto started Sync (also on your device: [see this issue](https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-media-communications-syncdelegate-blocks-charging)), I have implemented two versions of the sync. It might be that even manually, one of the two is not working. I will try and implement a choice option to choose the old or new version. Will probably be somewhere next week.
